### PR TITLE
Prepare SDK release 3.0

### PR DESCRIPTION
**Pull request by payoto**

### CODE REVIEW

**Comment by rahult-graphcore** [comment]
Commit [642b91d](https://github.com/graphcore/Graphcore-Pytorch-fork/pull/3/commits/642b91d38c9520be41d3149842e9a691f59c5c19) made using config https://github.com/graphcore/paperspace-automation/blob/1270d082d2bbbab198dc8a0200621bc86a1f76f1/releases/3.0.0/deploy-pytorch-paperspace.yaml

**Comment by rahult-graphcore** [comment]
Commit [4deb094](https://github.com/graphcore/Graphcore-Pytorch-fork/pull/3/commits/4deb0944a1f14bcfdc0e9beca6a19327a79d7336), pulled from tutorials internal repo for updated requirements file, using yaml: https://github.com/graphcore/paperspace-automation/commit/9c8ec9e2b3cff5ce78504c3dede822f6f3a9bd4a

**Comment by rahult-graphcore** [comment]
Commit [9169d28](https://github.com/graphcore/Graphcore-Pytorch-fork/pull/3/commits/9169d28c3d5d7eaedb3ae497f7a562ee13d51d83) pulls the requirements file for the basics tutorial from phabricator, fixing the torchvision version. Using yaml: https://github.com/graphcore/paperspace-automation/commit/c3aaf22863bf9f59d9b62a9090791d817544797d

**Comment by nmb-paperspace** [comment]
@payoto I can comment here, but clicking the YAMLs says 404

**Comment by nmb-paperspace** [comment]
OK. I can see the PRs and the resulting repo structure. Presumably I need to run the notebooks to see if they work to be able to comment the most usefully, which in turn needs the production cluster to be up from engineering. I think that may be today. As you mentioned, I can refer to the git commit hashes when starting the Gradient Notebooks to get the right version of the repos in the workspaces.

**Comment by payoto** [comment]
Closing to open the PRs into main

**Pull request closed without merging**
